"""
Tests unitarios PUROS del motor de diff estructural (``schema_diff``): sin cliente ni
motor, con fixtures ``SchemaSnapshot`` en memoria.

Cobertura:
- Un caso por "trampa" de normalización (debe dar CERO diff).
- Un caso por tipo de cambio (debe generar el ítem + flags esperados).
- Clasificación destructiva fail-closed.
- Heurística de rename (advisory).
- Orden por fases del pipeline.

Convención de estilo: helpers ``_col``/``_tbl``/``_snap`` (igual que test_snapshot_layout.py).
"""


from app.services.db_admin import schema_diff as sd
from app.services.db_admin.dtos import (
    CheckConstraintInfo,
    ColumnInfo,
    EnumTypeInfo,
    ExtensionInfo,
    ForeignKeyInfo,
    IndexInfo,
    RoutineInfo,
    SchemaSnapshot,
    SequenceInfo,
    TableSchema,
    TriggerInfo,
    ViewInfo,
)


# --------------------------------------------------------------------------- #
# Helpers                                                                      #
# --------------------------------------------------------------------------- #
def _col(name, type_="int", nullable=True, default=None, **kw):
    return ColumnInfo(name=name, type=type_, nullable=nullable, default=default, **kw)


def _tbl(name, columns, *, pk=None, fks=None, indexes=None, uniques=None,
         checks=None, storage=None, comment=None, database="db"):
    return TableSchema(
        database=database, table=name, columns=columns, primary_key=pk or [],
        foreign_keys=fks or [], indexes=indexes or [], unique_constraints=uniques or [],
        check_constraints=checks or [], storage_options=storage or {}, comment=comment,
    )


def _snap(engine="mysql", *, tables=None, views=None, routines=None, triggers=None,
          sequences=None, enum_types=None, extensions=None, events=None):
    return SchemaSnapshot(
        database="db", source_engine=engine, tables=tables or [], views=views or [],
        routines=routines or [], triggers=triggers or [], sequences=sequences or [],
        enum_types=enum_types or [], extensions=extensions or [], events=events or [],
    )


def _items_by(diff, object_type=None, change_type=None):
    out = diff.items
    if object_type is not None:
        out = [i for i in out if i.object_type == object_type]
    if change_type is not None:
        out = [i for i in out if i.change_type == change_type]
    return out


# =========================================================================== #
# TRAMPAS DE NORMALIZACIÓN — deben dar CERO diff                               #
# =========================================================================== #
def test_identical_snapshots_zero_diff():
    t = _tbl("users", [_col("id", "int"), _col("name", "varchar(50)")], pk=["id"])
    assert diff_items(_snap(tables=[t]), _snap(tables=[t])) == []


def test_int_display_width_is_not_a_diff_mysql():
    # int(11) (MySQL 5.7) vs int (MySQL 8) -> mismo tipo canónico.
    src = _tbl("t", [_col("id", "int")], pk=["id"])
    tgt = _tbl("t", [_col("id", "int(11)")], pk=["id"])
    assert diff_items(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt])) == []


def test_pg_default_cast_is_not_a_diff():
    # PG agrega ::character varying al default; no debe verse como cambio.
    src = _tbl("t", [_col("s", "varchar(10)", default="'x'")])
    tgt = _tbl("t", [_col("s", "varchar(10)", default="'x'::character varying")])
    assert diff_items(_snap("postgresql", tables=[src]),
                      _snap("postgresql", tables=[tgt])) == []


def test_current_timestamp_forms_are_not_a_diff():
    src = _tbl("t", [_col("c", "datetime", default="CURRENT_TIMESTAMP")])
    tgt = _tbl("t", [_col("c", "datetime", default="current_timestamp()")])
    assert diff_items(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt])) == []


def test_collation_equal_to_table_default_is_not_a_diff():
    # La columna hereda el default de la tabla en ambos lados -> no diff.
    src = _tbl("t", [_col("s", "varchar(10)", collation="utf8mb4_general_ci")],
               storage={"collation": "utf8mb4_general_ci"})
    tgt = _tbl("t", [_col("s", "varchar(10)", collation="utf8mb4_general_ci")],
               storage={"collation": "utf8mb4_general_ci"})
    assert diff_items(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt])) == []


def test_autogenerated_fk_name_is_not_a_diff():
    # Mismo FK por definición, distinto nombre autogenerado -> no diff.
    fk_a = ForeignKeyInfo(name="orders_ibfk_1", columns=["uid"], referred_table="users",
                          referred_columns=["id"])
    fk_b = ForeignKeyInfo(name="fk_orders_users", columns=["uid"], referred_table="users",
                          referred_columns=["id"])
    src = _tbl("orders", [_col("uid", "int")], fks=[fk_a])
    tgt = _tbl("orders", [_col("uid", "int")], fks=[fk_b])
    assert diff_items(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt])) == []


def test_autogenerated_index_name_is_not_a_diff():
    ix_a = IndexInfo(name="ix_auto_1", columns=["email"], unique=True)
    ix_b = IndexInfo(name="uq_email", columns=["email"], unique=True)
    src = _tbl("u", [_col("email", "varchar(20)")], indexes=[ix_a])
    tgt = _tbl("u", [_col("email", "varchar(20)")], indexes=[ix_b])
    assert diff_items(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt])) == []


def test_column_order_is_not_a_diff():
    src = _tbl("t", [_col("a", "int"), _col("b", "int")])
    tgt = _tbl("t", [_col("b", "int"), _col("a", "int")])
    assert diff_items(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt])) == []


def test_procedural_body_whitespace_is_not_a_diff():
    r_src = RoutineInfo(name="f", kind="FUNCTION", body="CREATE FUNCTION f() RETURNS int RETURN 1")
    r_tgt = RoutineInfo(name="f", kind="FUNCTION",
                        body="CREATE  FUNCTION   f()   RETURNS int   RETURN 1;")
    assert diff_items(_snap("mysql", routines=[r_src]),
                      _snap("mysql", routines=[r_tgt])) == []


def test_definer_clause_in_body_is_not_a_diff():
    r_src = RoutineInfo(name="f", kind="FUNCTION",
                        body="CREATE FUNCTION f() RETURNS int RETURN 1")
    r_tgt = RoutineInfo(name="f", kind="FUNCTION",
                        body="CREATE DEFINER=`root`@`localhost` FUNCTION f() RETURNS int RETURN 1")
    assert diff_items(_snap("mysql", routines=[r_src]),
                      _snap("mysql", routines=[r_tgt])) == []


def test_extension_version_only_diff_is_ignored():
    src = _snap("postgresql", extensions=[ExtensionInfo(name="citext", version="1.6")])
    tgt = _snap("postgresql", extensions=[ExtensionInfo(name="citext", version="1.5")])
    assert diff_items(src, tgt) == []


def test_sequence_last_value_is_never_compared():
    # SequenceInfo no tiene last_value; misma definición estructural -> no diff.
    s = SequenceInfo(name="s", data_type="bigint", increment=1, min_value=1, max_value=100)
    assert diff_items(_snap("postgresql", sequences=[s]),
                      _snap("postgresql", sequences=[s])) == []


# =========================================================================== #
# TIPOS DE CAMBIO — deben generar ítem + flags                                 #
# =========================================================================== #
def test_new_table_generates_new_item_phase_2():
    src = _snap("mysql", tables=[_tbl("t", [_col("id", "int")], pk=["id"])])
    tgt = _snap("mysql")
    diff = sd.diff_snapshots(src, tgt)
    news = _items_by(diff, "table", "new")
    assert len(news) == 1
    assert news[0].phase == sd.PHASE_CREATE_TABLE
    assert news[0].risk.destructive is False


def test_dropped_table_is_destructive_phase_8():
    src = _snap("mysql")
    tgt = _snap("mysql", tables=[_tbl("t", [_col("id", "int")], pk=["id"])])
    diff = sd.diff_snapshots(src, tgt)
    drops = _items_by(diff, "table", "dropped")
    assert len(drops) == 1
    assert drops[0].risk.destructive is True
    assert drops[0].phase == sd.PHASE_DROP_TABLE


def test_new_nullable_column_is_additive_safe():
    src = _tbl("t", [_col("id", "int"), _col("extra", "int", nullable=True)])
    tgt = _tbl("t", [_col("id", "int")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "new")[0]
    assert it.object_name == "t.extra"
    assert it.risk.destructive is False
    assert it.risk.needs_review is False
    assert it.phase == sd.PHASE_ALTER_ADDITIVE


def test_new_not_null_column_without_default_needs_review():
    src = _tbl("t", [_col("id", "int"), _col("req", "int", nullable=False)])
    tgt = _tbl("t", [_col("id", "int")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "new")[0]
    assert it.risk.needs_review is True


def test_dropped_column_is_destructive_phase_7():
    src = _tbl("t", [_col("id", "int")])
    tgt = _tbl("t", [_col("id", "int"), _col("old", "int")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "dropped")[0]
    assert it.object_name == "t.old"
    assert it.risk.destructive is True
    assert it.phase == sd.PHASE_ALTER_DESTRUCTIVE


def test_type_narrowing_is_destructive():
    # bigint -> int (achicar) sobre el target.
    src = _tbl("t", [_col("n", "int")])
    tgt = _tbl("t", [_col("n", "bigint")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert "type" in it.changed_attributes
    assert it.risk.destructive is True
    assert it.risk.data_conversion is True


def test_varchar_shrink_is_destructive():
    src = _tbl("t", [_col("s", "varchar(50)")])
    tgt = _tbl("t", [_col("s", "varchar(255)")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert it.risk.destructive is True


def test_varchar_widen_is_not_destructive():
    src = _tbl("t", [_col("s", "varchar(255)")])
    tgt = _tbl("t", [_col("s", "varchar(50)")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert it.risk.destructive is False
    assert it.risk.lock_heavy is True


def test_drop_default_is_destructive():
    src = _tbl("t", [_col("s", "int", default=None)])
    tgt = _tbl("t", [_col("s", "int", default="0")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert "default" in it.changed_attributes
    assert it.risk.destructive is True


def test_collation_change_is_destructive():
    src = _tbl("t", [_col("s", "varchar(10)", collation="utf8mb4_bin")],
               storage={"collation": "utf8mb4_general_ci"})
    tgt = _tbl("t", [_col("s", "varchar(10)", collation="utf8mb4_general_ci")],
               storage={"collation": "utf8mb4_general_ci"})
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert "collation" in it.changed_attributes
    assert it.risk.destructive is True


def test_pg_type_change_incompatible_family_needs_review():
    # text -> integer en PG requiere USING (conversión).
    src = _tbl("t", [_col("v", "integer")])
    tgt = _tbl("t", [_col("v", "text")])
    diff = sd.diff_snapshots(_snap("postgresql", tables=[src]),
                             _snap("postgresql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert it.risk.needs_review is True
    assert it.risk.data_conversion is True


def test_new_fk_is_additive_and_all_fks_phase_3():
    fk = ForeignKeyInfo(columns=["uid"], referred_table="users", referred_columns=["id"])
    src = _tbl("orders", [_col("uid", "int")], fks=[fk])
    tgt = _tbl("orders", [_col("uid", "int")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "foreign_key", "new")[0]
    assert it.phase == sd.PHASE_ALTER_ADDITIVE
    assert it.risk.destructive is False


def test_fk_option_change_is_modified_and_destructive():
    fk_src = ForeignKeyInfo(columns=["uid"], referred_table="users",
                            referred_columns=["id"], on_delete="CASCADE")
    fk_tgt = ForeignKeyInfo(columns=["uid"], referred_table="users",
                            referred_columns=["id"], on_delete="RESTRICT")
    src = _tbl("orders", [_col("uid", "int")], fks=[fk_src])
    tgt = _tbl("orders", [_col("uid", "int")], fks=[fk_tgt])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    mods = _items_by(diff, "foreign_key", "modified")
    assert len(mods) == 1
    assert mods[0].risk.destructive is True  # drop+add


def test_dropped_index_is_destructive():
    src = _tbl("t", [_col("a", "int")])
    tgt = _tbl("t", [_col("a", "int")], indexes=[IndexInfo(name="ix_a", columns=["a"], unique=False)])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "index", "dropped")[0]
    assert it.risk.destructive is True
    assert it.phase == sd.PHASE_ALTER_DESTRUCTIVE


def test_new_view_requires_individual_review():
    v = ViewInfo(name="v", definition="SELECT 1")
    diff = sd.diff_snapshots(_snap("mysql", views=[v]), _snap("mysql"))
    it = _items_by(diff, "view", "new")[0]
    assert it.risk.requires_individual_review is True
    assert it.risk.destructive is False
    assert it.phase == sd.PHASE_CREATE_REPLACE


def test_modified_routine_requires_individual_review():
    r_src = RoutineInfo(name="f", kind="FUNCTION", body="CREATE FUNCTION f() RETURNS int RETURN 2")
    r_tgt = RoutineInfo(name="f", kind="FUNCTION", body="CREATE FUNCTION f() RETURNS int RETURN 1")
    diff = sd.diff_snapshots(_snap("mysql", routines=[r_src]), _snap("mysql", routines=[r_tgt]))
    it = _items_by(diff, "routine", "modified")[0]
    assert it.risk.requires_individual_review is True


def test_dropped_trigger_is_destructive():
    t = TriggerInfo(name="trg", table="users", timing="BEFORE", events=["INSERT"],
                    action="CREATE TRIGGER trg BEFORE INSERT ON users FOR EACH ROW SET NEW.x=1")
    diff = sd.diff_snapshots(_snap("mysql"), _snap("mysql", triggers=[t]))
    it = _items_by(diff, "trigger", "dropped")[0]
    assert it.risk.destructive is True
    assert it.phase == sd.PHASE_DROP_DEPENDENT


def test_pg_enum_add_value_is_needs_review_not_destructive():
    src = _snap("postgresql", enum_types=[EnumTypeInfo(name="mood", values=["sad", "ok", "happy"])])
    tgt = _snap("postgresql", enum_types=[EnumTypeInfo(name="mood", values=["sad", "ok"])])
    it = _items_by(sd.diff_snapshots(src, tgt), "enum_type", "modified")[0]
    assert it.risk.needs_review is True
    assert it.risk.destructive is False


def test_pg_enum_remove_value_is_destructive():
    src = _snap("postgresql", enum_types=[EnumTypeInfo(name="mood", values=["sad", "ok"])])
    tgt = _snap("postgresql", enum_types=[EnumTypeInfo(name="mood", values=["sad", "ok", "happy"])])
    it = _items_by(sd.diff_snapshots(src, tgt), "enum_type", "modified")[0]
    assert it.risk.destructive is True


def test_mysql_enum_column_add_value_via_type_string():
    # En MySQL el ENUM es parte del tipo de la columna.
    src = _tbl("t", [_col("m", "enum('a','b','c')")])
    tgt = _tbl("t", [_col("m", "enum('a','b')")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert "type" in it.changed_attributes
    # agregar valores no es narrowing
    assert it.risk.destructive is False


def test_mysql_enum_column_remove_value_is_destructive():
    src = _tbl("t", [_col("m", "enum('a','b')")])
    tgt = _tbl("t", [_col("m", "enum('a','b','c')")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[src]), _snap("mysql", tables=[tgt]))
    it = _items_by(diff, "column", "modified")[0]
    assert it.risk.destructive is True


# =========================================================================== #
# CROSS-FLAVOR MySQL <-> MariaDB                                               #
# =========================================================================== #
def test_cross_flavor_warning_flag_set():
    t = _tbl("t", [_col("id", "int")], pk=["id"])
    diff = sd.diff_snapshots(_snap("mysql", tables=[t]), _snap("mariadb", tables=[t]))
    assert diff.cross_flavor_warning is True


def test_cross_flavor_warning_propagates_to_items():
    src = _snap("mysql", tables=[_tbl("t", [_col("id", "int"), _col("x", "int")])])
    tgt = _snap("mariadb", tables=[_tbl("t", [_col("id", "int")])])
    diff = sd.diff_snapshots(src, tgt)
    assert all(i.risk.cross_flavor_warning for i in diff.items)
    assert diff.items  # hubo al menos un ítem


def test_same_engine_no_cross_flavor():
    t = _tbl("t", [_col("id", "int")])
    diff = sd.diff_snapshots(_snap("mysql", tables=[t]), _snap("mysql", tables=[t]))
    assert diff.cross_flavor_warning is False


# =========================================================================== #
# RENAME HEURÍSTICO (advisory) — nunca autogenera RENAME                       #
# =========================================================================== #
def test_table_rename_heuristic_marks_both_items():
    cols = [_col("id", "int"), _col("name", "varchar(50)"), _col("email", "varchar(80)")]
    src = _snap("mysql", tables=[_tbl("clients", cols)])   # nueva
    tgt = _snap("mysql", tables=[_tbl("customers", cols)])  # eliminada (misma firma)
    diff = sd.diff_snapshots(src, tgt)
    new = _items_by(diff, "table", "new")[0]
    drop = _items_by(diff, "table", "dropped")[0]
    assert new.risk.possible_rename_of == "customers"
    assert drop.risk.possible_rename_of == "clients"
    # possible_rename => destructivo (fail-closed): el DROP nunca se oculta.
    assert new.risk.destructive is True
    assert drop.risk.destructive is True


def test_unrelated_tables_are_not_flagged_as_rename():
    src = _snap("mysql", tables=[_tbl("a", [_col("x", "int")])])
    tgt = _snap("mysql", tables=[_tbl("b", [_col("y", "text"), _col("z", "date")])])
    diff = sd.diff_snapshots(src, tgt)
    assert _items_by(diff, "table", "new")[0].risk.possible_rename_of is None
    assert _items_by(diff, "table", "dropped")[0].risk.possible_rename_of is None


# =========================================================================== #
# ORDEN POR FASES                                                              #
# =========================================================================== #
def test_phases_are_globally_ordered():
    # Construir un diff con objetos de varias fases y verificar orden monótono.
    src = _snap(
        "postgresql",
        extensions=[ExtensionInfo(name="citext")],           # fase 1 new
        tables=[_tbl("t", [_col("id", "int"), _col("new_col", "int")])],  # col new (fase 3)
        views=[ViewInfo(name="v", definition="SELECT 1")],   # fase 5 new
    )
    tgt = _snap(
        "postgresql",
        tables=[_tbl("t", [_col("id", "int"), _col("gone", "int")]),      # col dropped (fase 7)
                _tbl("old", [_col("id", "int")])],                        # tabla dropped (fase 8)
    )
    diff = sd.diff_snapshots(src, tgt)
    phases = [i.phase for i in diff.items]
    assert phases == sorted(phases)


def test_new_tables_ordered_topologically_by_fk():
    parent = _tbl("parent", [_col("id", "int")], pk=["id"])
    child = _tbl("child", [_col("id", "int"), _col("pid", "int")], pk=["id"],
                 fks=[ForeignKeyInfo(columns=["pid"], referred_table="parent",
                                     referred_columns=["id"])])
    src = _snap("mysql", tables=[child, parent])
    diff = sd.diff_snapshots(src, _snap("mysql"))
    new_tables = [i.object_name for i in _items_by(diff, "table", "new")]
    assert new_tables.index("parent") < new_tables.index("child")


def test_dropped_tables_ordered_reverse_topologically():
    parent = _tbl("parent", [_col("id", "int")], pk=["id"])
    child = _tbl("child", [_col("id", "int"), _col("pid", "int")], pk=["id"],
                 fks=[ForeignKeyInfo(columns=["pid"], referred_table="parent",
                                     referred_columns=["id"])])
    tgt = _snap("mysql", tables=[child, parent])
    diff = sd.diff_snapshots(_snap("mysql"), tgt)
    dropped = [i.object_name for i in _items_by(diff, "table", "dropped")]
    assert dropped.index("child") < dropped.index("parent")


# =========================================================================== #
# NORMALIZADORES (unidad)                                                      #
# =========================================================================== #
def test_canonical_type_strips_int_display_width():
    assert sd.canonical_type("int(11)", "mysql") == sd.canonical_type("int", "mysql")


def test_canonical_type_pg_aliases():
    assert sd.canonical_type("character varying(20)", "postgresql") == \
        sd.canonical_type("varchar(20)", "postgresql")


def test_normalize_default_strips_pg_cast():
    assert sd.normalize_default("'x'::character varying", "postgresql") == "'x'"


def test_normalize_default_unifies_current_timestamp():
    assert sd.normalize_default("CURRENT_TIMESTAMP", "mysql") == \
        sd.normalize_default("current_timestamp()", "mysql")


def test_is_narrowing_int_family():
    assert sd.is_narrowing("int", "bigint") is True
    assert sd.is_narrowing("bigint", "int") is False


# =========================================================================== #
# GENERACIÓN DE DDL (Fase 3) — pura sobre el diff, sin motor real              #
# =========================================================================== #
# render_diff() no abre conexión: es determinista sobre el SchemaDiff. Estos tests
# verifican la sintaxis por dialecto SIN Docker (la ejecución real queda sin verificar).
def _adapter(engine):
    from app.core.remote_engine import ServerTarget
    from app.services.db_admin.mysql_adapter import MariaDBAdapter, MySQLAdapter
    from app.services.db_admin.postgres_adapter import PostgresAdapter

    tgt = ServerTarget(1, engine, "h", 1, "u", "p")
    return {
        "mysql": MySQLAdapter, "mariadb": MariaDBAdapter, "postgresql": PostgresAdapter,
    }[engine](tgt)


def _render(engine, src, tgt):
    return _adapter(engine).render_diff(sd.diff_snapshots(src, tgt))


def test_render_mysql_create_table_uses_backticks_and_pk():
    src = _snap("mysql", tables=[_tbl(
        "users", [_col("id", "int", nullable=False), _col("email", "varchar(120)", nullable=False)],
        pk=["id"])])
    stmts = _render("mysql", src, _snap("mysql"))
    sqls = [s.sql for s in stmts]
    assert any(x.startswith("CREATE TABLE `users`") for x in sqls)
    assert any("PRIMARY KEY (`id`)" in x for x in sqls)


def test_render_mysql_modify_column_uses_full_modify():
    src = _snap("mysql", tables=[_tbl("t", [_col("s", "varchar(100)", nullable=False)])])
    tgt = _snap("mysql", tables=[_tbl("t", [_col("s", "varchar(50)", nullable=False)])])
    stmts = _render("mysql", src, tgt)
    assert any("MODIFY COLUMN `s` varchar(100) NOT NULL" in s.sql for s in stmts)


def test_render_pg_modify_type_emits_alter_column_type_with_using():
    src = _snap("postgresql", tables=[_tbl("t", [_col("v", "integer")])])
    tgt = _snap("postgresql", tables=[_tbl("t", [_col("v", "text")])])
    stmts = _render("postgresql", src, tgt)
    assert any('ALTER COLUMN "v" TYPE integer USING "v"::integer' in s.sql for s in stmts)


def test_render_pg_modify_column_is_per_attribute():
    # Cambia default y nullable a la vez -> dos sentencias separadas (PG no redefine).
    src = _snap("postgresql", tables=[_tbl("t", [_col("s", "text", nullable=False, default="'x'")])])
    tgt = _snap("postgresql", tables=[_tbl("t", [_col("s", "text", nullable=True, default=None)])])
    stmts = [s.sql for s in _render("postgresql", src, tgt)]
    assert any("SET NOT NULL" in x for x in stmts)
    assert any("SET DEFAULT 'x'" in x for x in stmts)


def test_render_mysql_drop_fk_uses_drop_foreign_key():
    fk = ForeignKeyInfo(name="fk1", columns=["uid"], referred_table="users", referred_columns=["id"])
    src = _snap("mysql", tables=[_tbl("o", [_col("uid", "int")])])
    tgt = _snap("mysql", tables=[_tbl("o", [_col("uid", "int")], fks=[fk])])
    assert any("DROP FOREIGN KEY `fk1`" in s.sql for s in _render("mysql", src, tgt))


def test_render_pg_drop_fk_uses_drop_constraint():
    fk = ForeignKeyInfo(name="fk1", columns=["uid"], referred_table="users", referred_columns=["id"])
    src = _snap("postgresql", tables=[_tbl("o", [_col("uid", "int")])])
    tgt = _snap("postgresql", tables=[_tbl("o", [_col("uid", "int")], fks=[fk])])
    assert any('DROP CONSTRAINT "fk1"' in s.sql for s in _render("postgresql", src, tgt))


def test_render_new_table_fk_is_separate_statement_not_inline():
    fk = ForeignKeyInfo(name="fk_c", columns=["pid"], referred_table="parent", referred_columns=["id"])
    child = _tbl("child", [_col("id", "int", nullable=False), _col("pid", "int")], pk=["id"], fks=[fk])
    parent = _tbl("parent", [_col("id", "int", nullable=False)], pk=["id"])
    stmts = _render("mysql", _snap("mysql", tables=[child, parent]), _snap("mysql"))
    child_ct = [s.sql for s in stmts if s.object_type == "table" and "`child`" in s.sql][0]
    assert "FOREIGN KEY" not in child_ct  # nunca inline
    assert any("ADD CONSTRAINT `fk_c` FOREIGN KEY" in s.sql for s in stmts)


def test_render_view_mysql_create_or_replace():
    v = ViewInfo(name="v", definition="select 1 as x")
    stmts = _render("mysql", _snap("mysql", views=[v]), _snap("mysql"))
    assert any(s.sql.startswith("CREATE OR REPLACE VIEW `v`") for s in stmts)


def test_render_matview_pg_modified_is_drop_create():
    v_src = ViewInfo(name="m", is_materialized=True, definition="select 2")
    v_tgt = ViewInfo(name="m", is_materialized=True, definition="select 1")
    stmts = [s.sql for s in _render("postgresql", _snap("postgresql", views=[v_src]),
                                    _snap("postgresql", views=[v_tgt]))]
    assert any("DROP MATERIALIZED VIEW IF EXISTS" in x for x in stmts)
    assert any("CREATE MATERIALIZED VIEW" in x for x in stmts)


def test_render_pg_enum_add_value():
    src = _snap("postgresql", enum_types=[EnumTypeInfo(name="mood", values=["a", "b", "c"])])
    tgt = _snap("postgresql", enum_types=[EnumTypeInfo(name="mood", values=["a", "b"])])
    stmts = [s.sql for s in _render("postgresql", src, tgt)]
    assert any("ALTER TYPE \"mood\" ADD VALUE 'c'" in x for x in stmts)


def test_rendered_statements_carry_risk_flags_from_diff():
    tgt = _snap("mysql", tables=[_tbl("t", [_col("id", "int")], pk=["id"])])
    stmts = _render("mysql", _snap("mysql"), tgt)
    drop = [s for s in stmts if s.object_type == "table"][0]
    assert drop.risk.destructive is True
    assert drop.change_type == "dropped"


def test_render_new_column_down_sql_is_confirmed_drop():
    src = _snap("mysql", tables=[_tbl("t", [_col("id", "int"), _col("x", "int", nullable=True)])])
    tgt = _snap("mysql", tables=[_tbl("t", [_col("id", "int")])])
    col = [s for s in _render("mysql", src, tgt) if s.object_type == "column"][0]
    assert col.down_confirmed is True
    assert "DROP COLUMN `x`" in col.down_sql


def test_render_mariadb_drop_check_uses_drop_constraint():
    ck = CheckConstraintInfo(name="ck1", sqltext="x > 0")
    src = _snap("mariadb", tables=[_tbl("t", [_col("x", "int")])])
    tgt = _snap("mariadb", tables=[_tbl("t", [_col("x", "int")], checks=[ck])])
    stmts = [s.sql for s in _render("mariadb", src, tgt)]
    assert any("DROP CONSTRAINT `ck1`" in x for x in stmts)


def test_render_mysql_drop_check_uses_drop_check():
    ck = CheckConstraintInfo(name="ck1", sqltext="x > 0")
    src = _snap("mysql", tables=[_tbl("t", [_col("x", "int")])])
    tgt = _snap("mysql", tables=[_tbl("t", [_col("x", "int")], checks=[ck])])
    stmts = [s.sql for s in _render("mysql", src, tgt)]
    assert any("DROP CHECK `ck1`" in x for x in stmts)


# =========================================================================== #
# Helper de aserción de "cero diff"                                            #
# =========================================================================== #
def diff_items(src, tgt):
    return sd.diff_snapshots(src, tgt).items
