"""add schema comparison tables

Revision ID: eb3aa0df3d42
Revises: d0e1f2a3b4c5
Create Date: 2026-07-13 08:07:12.548811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb3aa0df3d42'
down_revision: Union[str, None] = 'd0e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplica los cambios de esta migración.

    Esta función se ejecuta al hacer 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_comparisons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único de la comparación'),
    sa.Column('source_database_id', sa.Integer(), nullable=False, comment='BD de referencia (estado deseado). El diff describe cómo llevar TARGET a este estado'),
    sa.Column('target_database_id', sa.Integer(), nullable=False, comment='BD que se modificaría (recibe el DDL derivado)'),
    sa.Column('source_engine', sa.String(length=20), nullable=False, comment="Motor del source al comparar ('mysql'|'mariadb'|'postgresql')"),
    sa.Column('target_engine', sa.String(length=20), nullable=False, comment='Motor del target (el DDL se renderiza para este dialecto)'),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False, comment='SHA256 del snapshot normalizado del source al comparar (anti-TOCTOU)'),
    sa.Column('target_fingerprint', sa.String(length=64), nullable=False, comment='SHA256 del snapshot normalizado del target al comparar (anti-TOCTOU)'),
    sa.Column('cross_flavor_warning', sa.Boolean(), server_default='0', nullable=False, comment='True si es una comparación MySQL↔MariaDB (posible ruido de dialecto)'),
    sa.Column('scope_note', sa.Text(), nullable=True, comment="Aviso de alcance (p. ej. PostgreSQL: solo schema 'public')"),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Vencimiento (TTL): tras expirar, adopt/execute exigen recalcular (410)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.ForeignKeyConstraint(['source_database_id'], ['managed_databases.id'], name=op.f('fk_schema_comparisons_source_database_id_managed_databases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_database_id'], ['managed_databases.id'], name=op.f('fk_schema_comparisons_target_database_id_managed_databases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_comparisons')),
    comment='Cabecera de una comparación estructural entre dos BDs gestionadas'
    )
    with op.batch_alter_table('schema_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_comparisons_source_database_id'), ['source_database_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_comparisons_target_database_id'), ['target_database_id'], unique=False)

    op.create_table('schema_comparison_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único de la sentencia'),
    sa.Column('comparison_id', sa.Integer(), nullable=False, comment='Comparación a la que pertenece esta sentencia'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='Orden GLOBAL de aplicación (render order, ya por fase 1..9)'),
    sa.Column('object_type', sa.String(length=40), nullable=False, comment='table|column|index|foreign_key|view|routine|trigger|sequence|enum_type|…'),
    sa.Column('object_name', sa.String(length=512), nullable=False, comment='Nombre del objeto (cualificado con su tabla padre donde aplica)'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='new | modified | dropped'),
    sa.Column('phase', sa.Integer(), nullable=False, comment='Fase del pipeline de aplicación (1..9)'),
    sa.Column('sql', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='Sentencia DDL renderizada para el motor del target'),
    sa.Column('risk_flags', sa.Text(), nullable=False, comment='JSON de RiskFlags (destructive/lock_heavy/data_conversion/needs_review/requires_individual_review/cross_flavor_warning/possible_rename_of)'),
    sa.Column('down_sql', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='Reverso de esta sentencia (sugerido por el renderer); NULL si no aplica'),
    sa.Column('down_confirmed', sa.Boolean(), server_default='0', nullable=False, comment='True si el reverso es claramente seguro (aditivo) — auto-confirmable'),
    sa.Column('execution_status', sa.String(length=20), nullable=True, comment='Resultado de la ejecución ad-hoc: applied | failed | skipped (NULL = no ejecutada)'),
    sa.Column('execution_error', sa.Text(), nullable=True, comment='Error del motor si la sentencia falló (limpio, sin secretos)'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='Momento de ejecución de esta sentencia'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.ForeignKeyConstraint(['comparison_id'], ['schema_comparisons.id'], name=op.f('fk_schema_comparison_items_comparison_id_schema_comparisons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_comparison_items')),
    comment='Sentencia DDL derivada de una comparación (una fila por sentencia)'
    )
    with op.batch_alter_table('schema_comparison_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_comparison_items_comparison_id'), ['comparison_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revierte los cambios de esta migración.

    Esta función se ejecuta al hacer 'alembic downgrade'.
    """
    # NOTA: se removieron los `drop_index(...)` explícitos que autogenerate emitió antes
    # de cada `drop_table(...)` (patrón por defecto, replicado en migraciones anteriores
    # de este repo). En MySQL/MariaDB falla: no se puede soltar un índice mientras siga
    # respaldando la FK de la propia tabla ("Cannot drop index ...: needed in a foreign
    # key constraint"), verificado contra MariaDB 11 real. `drop_table` ya elimina el
    # índice junto con la tabla y su FK — el drop explícito es redundante y, en estos dos
    # motores, roto. SQLite no lo detecta porque no aplica esa restricción.
    op.drop_table('schema_comparison_items')
    op.drop_table('schema_comparisons')
