"""inventory: servers

Revision ID: 71f0ca615549
Revises: 
Create Date: 2026-06-11 07:29:56.453200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f0ca615549'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplica los cambios de esta migración.

    Esta función se ejecuta al hacer 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único del servidor'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Alias legible del servidor'),
    sa.Column('host', sa.String(length=255), nullable=False, comment='Hostname o IP del servidor destino'),
    sa.Column('port', sa.Integer(), nullable=False, comment='Puerto de conexión del motor'),
    sa.Column('engine', sa.Enum('mysql', 'mariadb', 'postgresql', name='enginetype', native_enum=False, length=20), nullable=False, comment='Motor de base de datos: mysql | mariadb | postgresql'),
    sa.Column('root_username', sa.String(length=128), nullable=False, comment='Usuario pseudo-root para administrar el servidor'),
    sa.Column('root_password_encrypted', sa.Text(), nullable=False, comment='Password pseudo-root CIFRADO (Fernet). Nunca se expone ni se loguea'),
    sa.Column('status', sa.Enum('active', 'inactive', 'unreachable', name='serverstatus', native_enum=False, length=20), server_default='active', nullable=False, comment='Estado operativo del servidor en el inventario'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Permite deshabilitar el servidor sin borrarlo (soft-disable)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas adicionales sobre el servidor'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('host', 'port', name='uq_servers_host_port'),
    comment='Servidores de base de datos destino administrados por el gateway'
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único del usuario'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nombre de usuario único para login'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Correo electrónico único del usuario'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Contraseña hasheada (bcrypt/argon2)'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='Nombre completo del usuario'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas adicionales sobre el usuario'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Indica si el usuario está activo en el sistema'),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False, comment='Indica si el usuario tiene privilegios de superusuario'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Tabla de usuarios del sistema'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revierte los cambios de esta migración.

    Esta función se ejecuta al hacer 'alembic downgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_name'))

    op.drop_table('servers')
    # ### end Alembic commands ###
