"""iteration 2: server_users, database_models, managed_databases, audit_log

Revision ID: 5429b83cc392
Revises: 71f0ca615549
Create Date: 2026-06-11 12:47:02.560823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5429b83cc392'
down_revision: Union[str, None] = '71f0ca615549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplica los cambios de esta migración.

    Esta función se ejecuta al hacer 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True, comment='Request ID de la operación'),
    sa.Column('admin_id', sa.Integer(), nullable=True, comment='ID del admin que ejecutó la acción'),
    sa.Column('admin_username', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False, comment="Acción, p. ej. 'managed_database.create'"),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('touched_engine', sa.Boolean(), server_default='0', nullable=False, comment='True si la operación ejecutó DDL/DCL en un motor destino'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success | error'),
    sa.Column('detail', sa.Text(), nullable=True, comment='Resumen corto SIN credenciales'),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    comment='Auditoría de operaciones sensibles del gateway'
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_server_id'), ['server_id'], unique=False)

    op.create_table('database_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único del blueprint'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Nombre legible del blueprint (p. ej. 'Whatsapp')"),
    sa.Column('slug', sa.String(length=120), nullable=False, comment='Identificador estable en kebab/snake-case'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del blueprint'),
    sa.Column('current_version', sa.String(length=50), server_default='0.0.0', nullable=False, comment='Versión actual del blueprint (string libre por ahora)'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft-disable del blueprint'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_models')),
    comment='Blueprints/categorías de base de datos (plantillas lógicas)'
    )
    with op.batch_alter_table('database_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_models_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_database_models_slug'), ['slug'], unique=True)

    op.create_table('server_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único del usuario'),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='Servidor destino al que pertenece el usuario'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='Nombre del usuario/rol en el motor'),
    sa.Column('host', sa.String(length=255), server_default='%', nullable=False, comment="Host MySQL ('user'@'host'); ignorado en PostgreSQL"),
    sa.Column('password_encrypted', sa.Text(), nullable=True, comment='Password del usuario CIFRADO (Fernet), opcional. Nunca se expone'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft-disable del usuario en el inventario'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas adicionales sobre el usuario'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_users_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_users')),
    sa.UniqueConstraint('server_id', 'username', 'host', name='uq_server_users_server_username_host'),
    comment='Usuarios del motor (propietarios) gestionados por el gateway'
    )
    with op.batch_alter_table('server_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_users_server_id'), ['server_id'], unique=False)

    op.create_table('managed_databases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único de la BD gestionada'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Nombre de la base de datos en el motor'),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='Servidor donde vive la base de datos'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Usuario del motor propietario (único). RESTRICT: reasignar antes de borrar'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='Blueprint que replica esta BD (opcional)'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='Versión del blueprint implementada'),
    sa.Column('charset', sa.String(length=64), nullable=True, comment='Charset (MySQL/MariaDB); p. ej. utf8mb4'),
    sa.Column('collation', sa.String(length=64), nullable=True, comment='Collation (MySQL/MariaDB)'),
    sa.Column('status', sa.Enum('pending', 'active', 'error', 'archived', name='provisionstatus', native_enum=False, length=20), server_default='pending', nullable=False, comment='Estado de consistencia inventario↔motor'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas / detalle de error de aprovisionamiento'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha y hora de última actualización del registro'),
    sa.ForeignKeyConstraint(['model_id'], ['database_models.id'], name=op.f('fk_managed_databases_model_id_database_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['server_users.id'], name=op.f('fk_managed_databases_owner_id_server_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_managed_databases_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managed_databases')),
    sa.UniqueConstraint('server_id', 'name', name='uq_managed_databases_server_name'),
    comment='Bases de datos reales gestionadas por el gateway en cada servidor'
    )
    with op.batch_alter_table('managed_databases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_databases_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_databases_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_databases_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revierte los cambios de esta migración.

    Esta función se ejecuta al hacer 'alembic downgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_databases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_databases_server_id'))
        batch_op.drop_index(batch_op.f('ix_managed_databases_owner_id'))
        batch_op.drop_index(batch_op.f('ix_managed_databases_model_id'))

    op.drop_table('managed_databases')
    with op.batch_alter_table('server_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_users_server_id'))

    op.drop_table('server_users')
    with op.batch_alter_table('database_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_models_slug'))
        batch_op.drop_index(batch_op.f('ix_database_models_name'))

    op.drop_table('database_models')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_server_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
