-- Llenado del catálogo `privileges`
-- Generado por database/generate_schema.py desde los modelos ORM.
-- NO editar a mano: Alembic es la fuente de verdad del esquema.


-- El seeding REAL en runtime lo hace app/services/privilege_catalog.py
-- (idempotente y preservando is_active). Esto es la referencia SQL.

INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','ALL PRIVILEGES','object','Todos','Todos los privilegios del nivel (excluye GRANT OPTION)',1,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','ALTER','object','Tablas','Modificar la estructura de tablas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','ALTER ROUTINE','object','Rutinas','Modificar o eliminar rutinas almacenadas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE','object','Bases de datos, tablas','Crear bases de datos y tablas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE ROUTINE','object','Bases de datos','Crear procedimientos y funciones almacenadas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE TEMPORARY TABLES','object','Bases de datos','Crear tablas temporales',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE VIEW','object','Vistas','Crear o redefinir vistas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','DELETE','object','Tablas','Eliminar filas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','DROP','object','Bases de datos, tablas','Eliminar bases de datos y tablas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','EVENT','object','Bases de datos','Crear y gestionar eventos del scheduler',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','EXECUTE','object','Rutinas','Ejecutar procedimientos y funciones almacenadas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','GRANT OPTION','object','Delegación','Otorgar a otros los privilegios que uno posee',1,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','INDEX','object','Tablas','Crear o eliminar índices',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','INSERT','object','Tablas, columnas','Insertar filas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','LOCK TABLES','object','Bases de datos','Bloquear tablas con LOCK TABLES',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','REFERENCES','object','Tablas, columnas','Crear claves foráneas hacia la tabla',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','SELECT','object','Tablas, columnas','Leer filas de tablas o columnas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','SHOW VIEW','object','Vistas','Ver la definición de vistas (SHOW CREATE VIEW)',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','TRIGGER','object','Tablas','Crear, eliminar y ejecutar triggers',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','UPDATE','object','Tablas, columnas','Actualizar filas existentes',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','SUPER','admin','Servidor','Operaciones administrativas del servidor (en desuso)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','FILE','admin','Servidor','Leer/escribir archivos en el host del servidor',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','PROCESS','admin','Servidor','Ver los procesos de todos los usuarios',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','RELOAD','admin','Servidor','FLUSH y recarga de configuración',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','SHUTDOWN','admin','Servidor','Apagar el servidor',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE USER','admin','Servidor','Crear, renombrar y eliminar usuarios',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','SHOW DATABASES','admin','Servidor','Listar todas las bases de datos',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','REPLICATION CLIENT','admin','Servidor','Consultar el estado de replicación',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','REPLICATION SLAVE','admin','Servidor','Leer el binlog para replicación',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE TABLESPACE','admin','Servidor','Crear, alterar y eliminar tablespaces',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','CREATE ROLE','admin','Servidor','Crear roles',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mysql','DROP ROLE','admin','Servidor','Eliminar roles',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','ALL PRIVILEGES','object','Todos','Todos los privilegios del nivel (excluye GRANT OPTION)',1,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','ALTER','object','Tablas','Modificar la estructura de tablas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','ALTER ROUTINE','object','Rutinas','Modificar o eliminar rutinas almacenadas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE','object','Bases de datos, tablas','Crear bases de datos y tablas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE ROUTINE','object','Bases de datos','Crear procedimientos y funciones almacenadas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE TEMPORARY TABLES','object','Bases de datos','Crear tablas temporales',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE VIEW','object','Vistas','Crear o redefinir vistas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','DELETE','object','Tablas','Eliminar filas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','DELETE HISTORY','object','Tablas','Borrar historial de tablas versionadas por sistema',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','DROP','object','Bases de datos, tablas','Eliminar bases de datos y tablas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','EVENT','object','Bases de datos','Crear y gestionar eventos del scheduler',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','EXECUTE','object','Rutinas','Ejecutar procedimientos y funciones almacenadas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','GRANT OPTION','object','Delegación','Otorgar a otros los privilegios que uno posee',1,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','INDEX','object','Tablas','Crear o eliminar índices',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','INSERT','object','Tablas, columnas','Insertar filas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','LOCK TABLES','object','Bases de datos','Bloquear tablas con LOCK TABLES',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','REFERENCES','object','Tablas, columnas','Crear claves foráneas hacia la tabla',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SELECT','object','Tablas, columnas','Leer filas de tablas o columnas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SHOW VIEW','object','Vistas','Ver la definición de vistas (SHOW CREATE VIEW)',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','TRIGGER','object','Tablas','Crear, eliminar y ejecutar triggers',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','UPDATE','object','Tablas, columnas','Actualizar filas existentes',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SUPER','admin','Servidor','Operaciones administrativas del servidor (en desuso)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','FILE','admin','Servidor','Leer/escribir archivos en el host del servidor',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','PROCESS','admin','Servidor','Ver los procesos de todos los usuarios',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','RELOAD','admin','Servidor','FLUSH y recarga de configuración',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SHUTDOWN','admin','Servidor','Apagar el servidor',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE USER','admin','Servidor','Crear, renombrar y eliminar usuarios',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SHOW DATABASES','admin','Servidor','Listar todas las bases de datos',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','REPLICATION CLIENT','admin','Servidor','Consultar el estado de replicación',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','REPLICATION SLAVE','admin','Servidor','Leer el binlog para replicación',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE TABLESPACE','admin','Servidor','Crear, alterar y eliminar tablespaces',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CREATE ROLE','admin','Servidor','Crear roles',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','DROP ROLE','admin','Servidor','Eliminar roles',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','BINLOG ADMIN','admin','Servidor','Administrar el binlog y purgarlo',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','BINLOG MONITOR','admin','Servidor','Monitorear el binlog (SHOW BINLOG, etc.)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','BINLOG REPLAY','admin','Servidor','Reproducir eventos del binlog (BINLOG)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','CONNECTION ADMIN','admin','Servidor','Saltar límites de conexión y matar conexiones',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','FEDERATED ADMIN','admin','Servidor','Administrar tablas FederatedX',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','READ_ONLY ADMIN','admin','Servidor','Ignorar read_only del servidor',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','REPLICA MONITOR','admin','Servidor','Monitorear réplicas (SHOW REPLICA STATUS)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','REPLICATION MASTER ADMIN','admin','Servidor','Administrar la configuración de primario',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','REPLICATION SLAVE ADMIN','admin','Servidor','Administrar la réplica (START/STOP REPLICA)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SET USER','admin','Servidor','Definir un usuario distinto en DEFINER',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('mariadb','SLAVE MONITOR','admin','Servidor','Monitorear el estado de la réplica (heredado)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','ALL PRIVILEGES','object','Todos','Todos los privilegios aplicables al objeto',1,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','CONNECT','object','Bases de datos','Conectarse a la base de datos',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','CREATE','object','Bases de datos, esquemas','Crear objetos en la base de datos o esquema',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','DELETE','object','Tablas','Eliminar filas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','EXECUTE','object','Funciones, procedimientos','Ejecutar funciones y procedimientos',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','INSERT','object','Tablas, columnas','Insertar filas',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','MAINTAIN','object','Tablas','Mantenimiento: VACUUM, ANALYZE, REINDEX, CLUSTER, REFRESH (PG17)',1,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','REFERENCES','object','Tablas, columnas','Crear claves foráneas hacia la tabla',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','SELECT','object','Tablas, columnas, secuencias','Leer datos de tablas, columnas o secuencias',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','TEMPORARY','object','Bases de datos','Crear tablas temporales',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','TRIGGER','object','Tablas','Crear triggers sobre la tabla',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','TRUNCATE','object','Tablas','Vaciar tablas con TRUNCATE',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','UPDATE','object','Tablas, columnas, secuencias','Actualizar datos',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','USAGE','object','Esquemas, secuencias','Acceder al esquema o usar secuencias',0,1);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','SUPERUSER','admin','Atributo de rol','Superusuario: omite todas las comprobaciones',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','CREATEROLE','admin','Atributo de rol','Crear, alterar y eliminar roles',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','CREATEDB','admin','Atributo de rol','Crear bases de datos',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','REPLICATION','admin','Atributo de rol','Iniciar conexiones de replicación',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','BYPASSRLS','admin','Atributo de rol','Omitir las políticas de Row-Level Security',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','SET','admin','Parámetros','Cambiar parámetros de configuración (GRANT SET ON PARAMETER)',0,0);
INSERT INTO `privileges` (`engine`,`name`,`category`,`context`,`description`,`is_sensitive`,`is_active`) VALUES ('postgresql','ALTER SYSTEM','admin','Parámetros','Modificar parámetros con ALTER SYSTEM',0,0);
